### ISSUE TITLE
Prefabs UI doesn't exist

### ISSUE THREAD

**Issue by playr-lol** [depthso/Roblox-ImGUI#10]
yea it just isn't existance

**Comment by depthso** [comment]
Please describe your problem in more depth and provide steps to reproduce the issue. Thanks

**Comment by playr-lol** [comment]
![image](https://github.com/user-attachments/assets/fffeb103-8dcb-45c2-b67b-c6f27674f769)

**Comment by depthso** [comment]
Ah, I must have forgotten to update the link provided in the readme.. Doh! 😣 

The asset id will be linked in the library source. I will update this soon.. 

Thanks 👍

**Comment by playr-lol** [comment]
response in 2 minutes (did NOT expect that)

**Comment by playr-lol** [comment]
you could make the prefab also have a download version as a .rbxm

**Comment by depthso** [comment]
This is being resolved on the rewrite. Apologies for the wait
