### ISSUE TITLE
Checkbox Breaking

### ISSUE THREAD

**Issue by SeasonalKirito** [depthso/Roblox-ImGUI#6]
For some reason the checkbox just breaks, this is a part of my code that is related to the issue:
```lua
local god_mode = main:Checkbox({
	Label = "God Mode",
	Callback = function(self, Value)
		Script.Functions.GodMode(Value)
	end
})



--<< Functions >>--
function Script.Functions.GodMode(Value: boolean)
	if Value then
		for _, v in pairs(workspace:WaitForChild("Rooms"):GetDescendants()) do
			if v.Name == "Locker" and v:IsA("Model") then
				local original_cframe = lplr.Character.HumanoidRootPart.CFrame
				lplr.Character.HumanoidRootPart.CFrame = v:FindFirstChild("Base").CFrame
				v:FindFirstChild("Folder"):FindFirstChild("Enter"):InvokeServer()
				lplr.Character.HumanoidRootPart.CFrame = original_cframe
				break
			end
		end
		--Script.Functions.Log(console, "SUCCESS", "Enabled Godmode", "rgb(0, 204, 102)", true)
	else
		for _, v in pairs(workspace:WaitForChild("Rooms"):GetDescendants()) do
			if v.Name == "Locker" and v:IsA("Model") then
				local original_cframe = lplr.Character.HumanoidRootPart.CFrame
				lplr.Character.HumanoidRootPart.CFrame = v:FindFirstChild("Base").CFrame
				v:FindFirstChild("Folder"):FindFirstChild("Exit"):InvokeServer()
				lplr.Character.HumanoidRootPart.CFrame = original_cframe
				break
			end
		end
		--Script.Functions.Log(console, "SUCCESS", "Disabled Godmode", "rgb(0, 204, 102)", true)
	end
end
```

**Comment by depthso** [comment]
I'll look into this. 
What do you mean by 'breaking', what happens when it breaks?

**Comment by SeasonalKirito** [comment]
> I'll look into this. What do you mean by 'breaks', what happens when it breaks?

When it breaks it just stay on true (checkmarked) and i cant change it

**Comment by depthso** [comment]
> > I'll look into this. What do you mean by 'breaks', what happens when it breaks?
> 
> When it breaks it just stays on true (checkmarked) and i cant change it, if you want the full code its [here](https://github.com/SeasonalKirito/Andromeda/blob/main/places/12552538292.lua), its for the game "pressure"

Okay thank you, have you checked the Roblox console for a possible error? I will look into your script thank you 👍

**Comment by SeasonalKirito** [comment]
> > > I'll look into this. What do you mean by 'breaks', what happens when it breaks?
> > 
> > 
> > When it breaks it just stays on true (checkmarked) and i cant change it, if you want the full code its [here](https://github.com/SeasonalKirito/Andromeda/blob/main/places/12552538292.lua), its for the game "pressure"
> 
> Okay thank you, have you checked the Roblox console for a possible error? I will look into your script thank you 👍

Yes. i have checked the console, i had issues with this before but ignored them because there were no console errors

**Comment by depthso** [comment]
Currently rewriting the library, expect probably next week. 😱

Also I noticed you have utilised this library in a few of your scripts,
I love love to hear some feedback from you, if you have used any hacky methods to get around a library issue please let me know what these are and I will resolve them! Thanks 👍

**Comment by SeasonalKirito** [comment]
> Currently rewriting the library, expect probably next week. 😱
> 
> Also I noticed you have utilised this library in a few of your scripts, I love love to hear some feedback from you, if you have used any hacky methods to get around a library issue please let me know what these are and I will resolve them! Thanks 👍

This UI in my opinion is the best UI lib i have used in a while, i have not come across any fixes yet, also i noticed that there are a lot of features you have not added to the docs that are useful for example no resize or auto size.

There was this other UI lib i used before i found yours, its called [rbimgui-2](https://github.com/Singularity5490/rbimgui-2) it has not been updated in years but works pretty well, you can look into its code for examples as i have not come across issues in that UI lib before, thanks for the help.

**Comment by depthso** [comment]
> > Currently rewriting the library, expect probably next week. 😱
> > 
> > Also I noticed you have utilised this library in a few of your scripts, I love love to hear some feedback from you, if you have used any hacky methods to get around a library issue please let me know what these are and I will resolve them! Thanks 👍
> 
> This UI in my opinion is the best UI lib i have used in a while, i have not come across any fixes yet, also i noticed that there are a lot of features you have not added to the docs that are useful for example no resize or auto size.
> 
> There was this other UI lib i used before i found yours, its called [rbimgui-2](https://github.com/Singularity5490/rbimgui-2) it has not been updated in years but works pretty well, you can look into its code for examples as i have not come across issues in that UI lib before, thanks for the help.

I appreciate the info! I'll definitely update the wiki, apologies for information I missed out on.. 😞

**Comment by SeasonalKirito** [comment]
> > > Currently rewriting the library, expect probably next week. 😱
> > > Also I noticed you have utilised this library in a few of your scripts, I love love to hear some feedback from you, if you have used any hacky methods to get around a library issue please let me know what these are and I will resolve them! Thanks 👍
> > 
> > 
> > This UI in my opinion is the best UI lib i have used in a while, i have not come across any fixes yet, also i noticed that there are a lot of features you have not added to the docs that are useful for example no resize or auto size.
> > There was this other UI lib i used before i found yours, its called [rbimgui-2](https://github.com/Singularity5490/rbimgui-2) it has not been updated in years but works pretty well, you can look into its code for examples as i have not come across issues in that UI lib before, thanks for the help.
> 
> I appreciate the info! I'll definitely update the wiki, apologies for information I missed out on.. 😞

Its alright, the docs are good how they are right now, the information wasn't necessary so i understand

**Comment by SeasonalKirito** [comment]
have you gained any progress on the issue?

**Comment by depthso** [comment]
It seems an error caused by your callback would interfere with the checkbox animations but not the state. 
For now, I have moved the call for the callback and therefore the animations will now play even if the callback errors
